# Generated by Django 5.2.11 on 2026-03-08 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icea_core', '0002_patientepisode_fhir_linkage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICEAPlusComputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula_version', models.CharField(default='icea_plus_v1', max_length=64)),
                ('grain', models.CharField(default='episode', max_length=32)),
                ('rows', models.IntegerField(default=0)),
                ('status', models.CharField(default='ok', max_length=32)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('request_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ICEAPlusFormulaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='icea_plus_v1', max_length=64, unique=True)),
                ('label', models.CharField(default='ICEA+ v1 pilot composite index', max_length=255)),
                ('status', models.CharField(default='pilot', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('spec', models.JSONField(blank=True, default=dict)),
                ('protocol_hash', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='modelartifact',
            new_name='icea_core_m_name_d7db45_idx',
            old_name='icea_core_m_name_vers_8a8c88_idx',
        ),
        migrations.AddField(
            model_name='iceapluscomputation',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='icea_plus_computations', to='icea_core.modelartifact'),
        ),
        migrations.AddIndex(
            model_name='iceaplusformulaversion',
            index=models.Index(fields=['version', 'is_active'], name='icea_core_i_version_e08dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='iceapluscomputation',
            index=models.Index(fields=['created_at', 'formula_version'], name='icea_core_i_created_4ec2cc_idx'),
        ),
    ]
